export const aquaIconMap: Record<string, string> = {
  // Navigation & UI Semantic Keys
  "folder-closed": "/images/icons/folder-closed.png",
  "folder-open": "/images/icons/folder-open.png",
  "file": "/images/icons/document.png",
  "arrow-down": "/images/icons/arrow-down.png",
  "arrow-right": "/images/icons/arrow-right.png",

  // Content Emojis (Standard)
  "📁": "/images/icons/folder-closed.png",
  "📂": "/images/icons/folder-open.png",
  "📄": "/images/icons/document.png",
  "⭐": "/images/icons/star.png",
  "🔍": "/images/icons/search.png",
  "🧠": "/images/icons/brain.png",
  "🗄️": "/images/icons/database.png",
  "☁️": "/images/icons/cloud.png",
  "📜": "/images/icons/scroll.png",
  "🔒": "/images/icons/lock.png",
  "🤖": "/images/icons/robot.png",
  "🧮": "/images/icons/math.png",
  "💡": "/images/icons/lightbulb.png",
  "🛠️": "/images/icons/tools.png",
  "🚀": "/images/icons/rocket.png",
  "🐛": "/images/icons/bug.png",
  "🌐": "/images/icons/globe.png",
  "💬": "/images/icons/chat.png",
  "🖼️": "/images/icons/image.png",
  "🔊": "/images/icons/sound.png",
  "✅": "/images/icons/check.png",
  "❌": "/images/icons/cross.png",
  "🔥": "/images/icons/fire.png",
  "🖨️": "/images/icons/printer.png",
};
